Repository COVID-19-electronic-health-system/Corona-tracker, pull requests merged in 2020-03, with the labels that each got.

#36 Create themePalette.css
  client/src/css/themePalette.css
Labels: good first issue

#41 Theme palettehotfix
  client/src/components/WeeklyTracker.js
  client/src/components/WeeklyTrackerDay.js
  client/src/css/themePalette.css
Labels: bug

#46 Navbar
  client/src/components/App.js
  client/src/components/NavBar.js
  client/src/components/WeeklyTracker.js
  client/src/components/WeeklyTrackerDay.js
  client/src/css/NavBar.css
  client/src/css/themePalette.css
  client/src/img/Calendar_Three-Lines.svg
  client/yarn.lock
  design/wireframes/CORONATRACKER UI-List_Doctor-InfoCard.png
  design/wireframes/CORONATRACKER UI-List_Patients-InfoCard.png
Labels: good first issue

#65 Update README.md with contact section- "Questions Related to Stack?"
  README.md
Labels: documentation

#95 Add prettier config
  client/package.json
Labels: enhancement

#90 Created DiagnosticContainer scaffolding to fit interactive UI in it
  client/package-lock.json
  client/src/components/App.js
  client/src/components/DiagnosticContainer.js
  client/src/css/DiagnosticContainer.css
  client/src/css/Temperature.css
Labels: enhancement

#76 Setup basic Redux. Test store data avaliability in ChartJs.js component
  client/package-lock.json
  client/package.json
  client/src/components/ChartJs.js
  client/src/index.js
  client/src/redux/actions/actions.js
  client/src/redux/reducers/rootReducer.js
  client/src/setupTests.js
  client/src/tests/ChartJs.test.js
  client/src/tests/__snapshots__/ChartJs.test.js.snap
  client/yarn.lock
Labels: bug, enhancement

#154 Disclaimer component
  client/src/components/Disclaimer.js
Labels: Frontend, V1

#209 Added redux to disclaimer modal
  client/src/components/Disclaimer.js
  client/src/css/Disclaimer.css
  client/src/redux/actions/actions.js
  client/src/redux/actions/disclaimer.js
  client/src/redux/reducers/disclaimer.js
  client/src/redux/reducers/rootReducer.js
Labels: WIP: DO NOT MERGE

#296 HOTFIX: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#276 deleted unused CSS and transfer to Material-UI style
  client/src/components/App.js
  client/src/components/Calendar.js
  client/src/components/Card.js
  client/src/components/DiagnosticContainer.js
  client/src/components/Disclaimer.js
  client/src/components/FactQuizContainer.js
  client/src/components/FlashCards.js
  client/src/components/Layout.js
  client/src/components/Loding.js
  client/src/components/Login.js
  client/src/components/NavBar.js
  client/src/components/Slider.js
  client/src/components/Subscribe.js
  client/src/css/App.css
  client/src/css/Calendar.css
  client/src/css/DiagnosticContainer.css
  client/src/css/FlashCards.css
  client/src/css/Login.css
  client/src/css/NavBar.css
  client/src/css/Slider.css
  client/src/index.js
Labels: Frontend
