Repository COVID-19-electronic-health-system/Corona-tracker, pull requests merged in 2020-04, with the labels that each got.

#373 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#398 Create new survey flow
  client/package.json
  client/src/components/App.jsx
  client/src/components/DiagnosticContainer.jsx
  client/src/components/Layout.jsx
  client/src/components/SymptomsTracker.jsx
  client/src/components/Table.jsx
  client/src/components/Translations.jsx
  client/src/components/survey-view/checkbox-button/CheckboxButton.jsx
  client/src/components/survey-view/checkbox-button/SingleCheckboxButton.jsx
  client/src/components/survey-view/checkbox-button/constants.jsx
  client/src/components/survey/Survey.jsx
  client/src/components/survey/SurveyPage1.jsx
  client/src/components/survey/SurveyPage2.jsx
  client/src/components/survey/SurveyPage3.jsx
  client/src/redux/actions/actions.js
  client/src/redux/actions/survey.js
  client/src/redux/reducers/rootReducer.js
  client/src/redux/reducers/survey.js
  client/src/tests/SymptomsTracker.test.jsx
  client/src/tests/redux/reducers/survey.test.js
  client/src/tests/surveys/Survey.test.jsx
  client/src/tests/surveys/SurveyPage1.test.jsx
  client/src/tests/surveys/SurveyPage2.test.jsx
  client/src/tests/surveys/SurveyPage3.test.jsx
  client/src/tests/surveys/__snapshots__/Survey.test.jsx.snap
  client/src/tests/surveys/__snapshots__/SurveyPage1.test.jsx.snap
  client/src/tests/surveys/__snapshots__/SurveyPage2.test.jsx.snap
  client/src/tests/surveys/__snapshots__/SurveyPage3.test.jsx.snap
Labels: WIP: DO NOT MERGE

#487 ShareButtons component
  client/package.json
  client/src/components/ShareButtons.jsx
  client/src/tests/ShareButtons.test.jsx
  client/yarn.lock
Labels: Frontend, enhancement

#498 Static images to references updated to external storage
  client/package.json
  client/public/index.html
  client/src/components/Calendar.jsx
  client/src/components/Disclaimer.jsx
  client/src/components/Layout.jsx
  client/src/components/LogHealthSlider.jsx
  client/src/components/Login.jsx
  client/src/components/NotFoundPage.jsx
  client/src/components/OnboardUser.jsx
  client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap
  client/src/utils/imgUrl.js
Labels: WIP: DO NOT MERGE

#565 Update readme
  README.md
  Resources-to-use.md
Labels: documentation

#601 fixes: #596 Design readme
  client/package.json
  design/README.md
Labels: documentation

#625 Remove templates in favor of .github variants
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/stand_up_meeting .md
  .github/pull_request_template.md
Labels: documentation

#672 Added ROADMAP-TO-MVP.md to repo with features needed to get to MVP st…
  ROADMAP-TO-MVP.md
Labels: MVP, documentation
